//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipApplicationTest.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestConfiguration
    {
        public int Id { get; set; }
        public short QuestionNumber { get; set; }
        public System.TimeSpan TimeLimit { get; set; }
        public short MinimumScore { get; set; }
    }
}
